export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";

export const USER_LOAD_FAIL="USER_LOAD_FAIL";
export const USER_LOAD_REQUEST="USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS="USER_LOAD_SUCCESS";


export const CLEAR_ERRORS="CLEAR_ERRORS";